### ISSUE TITLE
failed to create symlink on CentOS6.4

### ISSUE THREAD

**Issue by matsumotory** [kazuho/jailing#7]
jailingとても楽しく使わせて頂いています。

早速ですが、CentOS6環境でjailingを使うと、

```
failed to create symlink(/var/httpd-jail/etc/ssl/certs -> ../pki/tls/certs):No such file or directory at /usr/local/bin/jailing line 107.
```

このように`etc/ssl/certs`がCentOS6では`../pki/tls/certs`からのリンクになっており、その際に`etc/ssl/certs`のディレクトリがjaili環境に作られていない事からlinkに失敗しているようです。

また、この際に`etc/ssl/certs`の上の階層を見る事から`BINDDIRS`の調整も必要かと思い、まずはissueで報告します。

**Comment by kazuho** [comment]
/etc/ssl/certs については、/etc/passwd 等の同じように初回にコピーをする形でもいいかなと思います。

つまり、`$root/etc/ssl/certs` がなければディレクトリを作り、その中に /etc/ssl/certs の各ファイル（の実体）をコピーする、という感じです。

/etc/pki の下は色々やばいものが含まれそうなので、jail 下には見せるべきではないのではないか、と考えています。

**Comment by kazuho** [comment]
#8 を確認したのち、以下の２点を鑑みて、CentOS においては必要なディレクトリを更に bind することにし、@tokuhirom にお願いしました。
- CentOS のディレクトリ構造としてリンク先が /etc/pki/tls/certs と /etc/pki/ca-trust 以下という、いずれも秘密情報の入りづらいディレクトリな点
- Ubuntu の /etc/tls/certs 内はディレクトリ内の symlink 等が多い点（上のコメントの方式は、これらのリンク構造を破壊する）

**Comment by matsumotory** [comment]
@kazuho ちょうどいまからpull-requestだそうと思っていたのですが、同様の変更がすでにされていたので動作も確認しました。ありがとうございます。その他、正常にCentOSで動かなかったのは、正規表現の`^`がいらなかったという問題でもありましたが、それも修正されていたのでこちらからは何もpull-request出すネタは残っておりません！ありがとうございます！

**Comment by kazuho** [comment]
いえいえ、@tokuhirom と @matsumoto-r さんのおかげです！ありがとうございます。
